name: shgp-env
channels:
  - conda-forge
  - plotly
dependencies:
  - python=3.10.4
  - numpy=1.22.3
  - plotly=5.10.0
  - gpflow=2.5.2
  - tensorflow-cpu=2.9.1
  - xarray=0.20.1
  - netcdf4=1.5.7
  - matplotlib=3.5.1